# Generated by Django 5.2.1 on 2026-09-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0004_report_promotion"),
        ("students", "0009_alter_student_id"),
        ("subjects", "0003_alter_subject_id"),
        ("teachers", "0003_alter_teacher_hire_date_alter_teacher_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term1", "Term 1"),
                            ("term2", "Term 2"),
                            ("term3", "Term 3"),
                        ],
                        default="term1",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2026)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="elearning/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("due_date", models.DateTimeField()),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_content",
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_content",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_content",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term1", "Term 1"),
                            ("term2", "Term 2"),
                            ("term3", "Term 3"),
                        ],
                        default="term1",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2026)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="elearning/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                ("video_url", models.URLField(blank=True, default="")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_content",
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_content",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_content",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True, default="")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="elearning/submissions/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="elearning.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elearning_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "student"),
                        name="unique_assignment_student_submission",
                    )
                ],
            },
        ),
    ]
