# Generated by Django 6.0.3 on 2026-03-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_created_at'),
        ('classes', '0002_alter_schoolclass_options'),
        ('students', '0003_alter_student_options_alter_student_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3')], default='term1', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
    ]
