# Generated by Django 5.2.1 on 2026-06-16 07:29

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_options_and_more"),
        ("classes", "0004_report_promotion"),
        ("students", "0009_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="year",
            field=models.PositiveIntegerField(
                default=apps.attendance.models._get_current_year
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["school_class", "term", "date"],
                name="attendance__school__00836a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["school_class", "term", "year", "status"],
                name="attendance__school__9b97ef_idx",
            ),
        ),
    ]
