# Generated by Django 5.2.1 on 2026-09-27 15:36

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendance_year_alter_attendance_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                default="present",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SchoolCalendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("mid_term_break", "Mid-Term Break"),
                            ("vacation", "Vacation"),
                            ("public_holiday", "Public Holiday"),
                            ("school_closure", "School Closure"),
                            ("staff_training", "Staff Training"),
                            ("special_event", "Special Event"),
                            ("other", "Other"),
                        ],
                        default="holiday",
                        max_length=40,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=apps.attendance.models._get_current_year
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("term1", "Term 1"),
                            ("term2", "Term 2"),
                            ("term3", "Term 3"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, default="")),
                ("is_school_day", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Calendar",
                "verbose_name_plural": "School Calendar",
                "ordering": ["start_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["year", "term", "start_date"],
                        name="attendance__year_e8b34d_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="attendance__start_d_641922_idx",
                    ),
                ],
            },
        ),
    ]
