# Generated by Django 6.0.3 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='LSAT-0000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
