# Generated by Django 5.2.1 on 2026-06-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_report_promotion"),
        ("subjects", "0003_alter_subject_id"),
        ("teachers", "0002_teacher_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="classes.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="subjects.subject",
            ),
        ),
    ]
