# Generated by Django 5.2.1 on 2026-08-07 01:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PettyCashFloat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        help_text="The GL account this float posts to. Must be an asset account.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_float",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        help_text="The staff member accountable for this float's cash on hand.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_floats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funding_account",
                    models.ForeignKey(
                        help_text="Bank/cash account the float is drawn from and replenished from.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funded_petty_cash_floats",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Replenishment"),
                            ("adjustment", "Adjustment"),
                            ("expense", "Expense"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="submitted",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "adjustment_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increase", "Increase (cash over)"),
                            ("decrease", "Decrease (cash short)"),
                        ],
                        help_text="Required, and only used, when transaction_type=adjustment.",
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="petty_cash/receipts/%Y/%m/"
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contra_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The other side of the journal entry: an expense account for expense claims, or a 'Cash Over/Short' style account for adjustments. Not used for replenishments, which always post against the float's funding_account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_transactions",
                        to="accounting.account",
                    ),
                ),
                (
                    "float",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounting.pettycashfloat",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_transaction",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_paid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["float", "status"],
                        name="accounting__float_i_aa80e1_idx",
                    ),
                    models.Index(fields=["date"], name="accounting__date_f0c2b1_idx"),
                    models.Index(
                        fields=["transaction_type"],
                        name="accounting__transac_bbb446_idx",
                    ),
                ],
            },
        ),
    ]
