# Generated by Django 5.1.15 on 2026-07-16 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('archive', 'Record Archived'), ('restore', 'Record Restored'), ('attendance_update', 'Attendance Updated'), ('result_upload', 'Result Uploaded'), ('fee_update', 'Fee Updated'), ('payment_processed', 'Payment Processed'), ('receipt_generated', 'Receipt Generated'), ('bill_generated', 'Bill Generated'), ('announcement_created', 'Announcement Created'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_suspended', 'User Suspended'), ('user_reinstated', 'User Reinstated'), ('role_changed', 'Role Changed'), ('permission_changed', 'Permission Changed'), ('password_reset', 'Password Reset'), ('pin_reset', 'PIN Reset'), ('api_action', 'API Action'), ('file_upload', 'File Uploaded'), ('notification_sent', 'Notification Sent')], max_length=32)),
                ('module', models.CharField(choices=[('auth', 'Authentication'), ('students', 'Students'), ('teachers', 'Teachers'), ('classes', 'Classes'), ('attendance', 'Attendance'), ('results', 'Results'), ('fees', 'Fees'), ('admissions', 'Admissions'), ('announcements', 'Announcements'), ('accounts', 'Accounts'), ('notifications', 'Notifications'), ('system', 'System')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('resource_repr', models.CharField(blank=True, default='', help_text="Human-readable label, e.g. 'Student: John Doe (STU-0012)'", max_length=255)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['module', '-created_at'], name='audit_audit_module_2edae4_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['status', '-created_at'], name='audit_audit_status_605d18_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]