# Generated by Django 5.2.1 on 2026-08-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(
                choices=[
                    ("auth", "Authentication"),
                    ("students", "Students"),
                    ("teachers", "Teachers"),
                    ("classes", "Classes"),
                    ("attendance", "Attendance"),
                    ("results", "Results"),
                    ("fees", "Fees"),
                    ("admissions", "Admissions"),
                    ("announcements", "Announcements"),
                    ("accounts", "Accounts"),
                    ("accounting", "Accounting"),
                    ("notifications", "Notifications"),
                    ("system", "System"),
                ],
                max_length=32,
            ),
        ),
    ]
