# Generated by Django 5.2.1 on 2026-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Failed Login"),
                    ("create", "Record Created"),
                    ("update", "Record Updated"),
                    ("delete", "Record Deleted"),
                    ("archive", "Record Archived"),
                    ("restore", "Record Restored"),
                    ("attendance_update", "Attendance Updated"),
                    ("result_upload", "Result Uploaded"),
                    ("fee_update", "Fee Updated"),
                    ("payment_processed", "Payment Processed"),
                    ("receipt_generated", "Receipt Generated"),
                    ("bill_generated", "Bill Generated"),
                    ("announcement_created", "Announcement Created"),
                    ("user_activated", "User Activated"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_suspended", "User Suspended"),
                    ("user_reinstated", "User Reinstated"),
                    ("role_changed", "Role Changed"),
                    ("permission_changed", "Permission Changed"),
                    ("password_reset", "Password Reset"),
                    ("pin_reset", "PIN Reset"),
                    ("login_unlocked", "Login Unlocked"),
                    ("api_action", "API Action"),
                    ("file_upload", "File Uploaded"),
                    ("notification_sent", "Notification Sent"),
                ],
                max_length=32,
            ),
        ),
    ]
