# Generated by Django 5.2.1 on 2026-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006 user account status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Drives is_active automatically — see apps/accounts/services.py:set_account_status().",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent archive action, for record-keeping.",
                null=True,
            ),
        ),
    ]
