# Generated by Django 6.0.3 on 2026-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('nursery_kg', 'Nursery/KG'), ('basic_1_6', 'Basic 1-6'), ('basic_7_9', 'Basic 7-9')], default='basic_7_9', max_length=20),
        ),
    ]
