# Generated by Django 6.0.3 on 2026-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
