# Generated by Django 6.0.3 on 2026-03-15 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admission_admission_number_and_more'),
        ('classes', '0003_schoolclass_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-application_date']},
        ),
        migrations.AddField(
            model_name='admission',
            name='alt_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='health_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admission',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='previous_school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admission',
            name='applied_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='admission',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
