# Generated by Django 6.0.3 on 2026-03-16 21:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_admission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
