# Generated by Django 6.0.3 on 2026-03-14 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0003_alter_student_options_alter_student_school_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('student', 'term')},
        ),
    ]
