# Generated by Django 6.0.3 on 2026-03-14 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fee_options_fee_created_at_fee_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='book_user_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='workbook_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
