# Generated by Django 5.2.1 on 2026-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0004_paymenttransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
